### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by SmokeShine** [drewbaumann/AskGPT#7]
Is it possible to use llama openai compatibility ?
https://github.com/ggerganov/llama.cpp/discussions/795

What changes would be required?

**Comment by Topping1** [comment]
You can use my fork to use the KoboldCpp API.
My fork: https://github.com/Topping1/AskKobold/tree/main
KoboldCpp: https://github.com/LostRuins/koboldcpp

**Comment by drewbaumann** [comment]
> Is it possible to use llama openai compatibility ? [ggerganov/llama.cpp#795](https://github.com/ggerganov/llama.cpp/discussions/795)
> 
> What changes would be required?

Using @Topping1 's fork may be easiest, but forking and pointing to a server running a spec mimicking openai's isn't too challenging. I could imagine a preference option where one could pick their model or supply an openAI style compatible API endpoint of their own for local LLMs.

**Comment by eMUQI** [comment]
> Using @Topping1 's fork may be easiest, but forking and pointing to a server running a spec mimicking openai's isn't too challenging. I could imagine a preference option where one could pick their model or supply an openAI style compatible API endpoint of their own for local LLMs.

I believe that making both apibase and module configurable options can meet customization needs and make this project more flexible.

**Comment by drewbaumann** [comment]
@eMUQI  Yes this would be great, and not too challenging. Usually all that's needed is to change the base URL to an OpenAI API clone. 

If I added this as an option would you rather see this in the config file like the API key or some form of on device configuration?

**Comment by eMUQI** [comment]
> @eMUQI Yes this would be great, and not too challenging. Usually all that's needed is to change the base URL to an OpenAI API clone.
> 
> If I added this as an option would you rather see this in the config file like the API key or some form of on device configuration?

Thank you for considering adding this feature. Personally, being able to configure it through a configuration file is already sufficient.

**Comment by drewbaumann** [comment]
@eMUQI I just created this PR which should address your needs: #12
